"""empty message

Revision ID: 35af8e7894da
Revises: 6bec5e4cec3a
Create Date: 2020-08-22 23:09:01.320923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35af8e7894da'
down_revision = '6bec5e4cec3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('Show', 'start_date')
    # ### end Alembic commands ###
